import { Router, type IRouter } from "express";
import healthRouter from "./health";
import patientsRouter from "./patients";
import staffRouter from "./staff";
import notificationsRouter from "./notifications";
import auditRouter from "./audit";
import sinanNotificationsRouter from "./sinan-notifications";
import authRouter from "./auth";
import socialNotesRouter from "./social-notes";
import nutritionalAssessmentsRouter from "./nutritional-assessments";
import pharmacyEntriesRouter from "./pharmacy-entries";
import transfersRouter from "./transfers";
import alertsRouter from "./alerts";
import bedsRouter from "./beds";
import devicesRouter from "./devices";
import backupRouter from "./backup";
import examRequestsRouter from "./exam-requests";
import patientAlertsRouter from "./patient-alerts";
import callsRouter from "./calls";
import allergiesRouter from "./allergies";
import consentsRouter from "./consents";
import deathsRouter from "./deaths";
import proceduresRouter from "./procedures";
import interconsultsRouter from "./interconsults";
import carePlansRouter from "./care-plans";
import controlledSubstancesRouter from "./controlled-substances";
import dispensationsRouter from "./dispensations";
import internalNotificationsRouter from "./internal-notifications";
import reportsRouter from "./reports";
import temposMetas from "./tempos-metas";
import inventoryRouter from "./inventory";
import { requireAuth } from "../middleware/require-auth";
import { auditWrite } from "../middleware/audit-write";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/calls", callsRouter);  // public GET /recent + auth POST /

router.use(requireAuth);
router.use(auditWrite);

router.use("/patients", patientsRouter);
router.use("/exam-requests", examRequestsRouter);
router.use("/patients/:id/notifications", notificationsRouter);
router.use("/patients/:id/social-notes", socialNotesRouter);
router.use("/patients/:id/nutritional-assessments", nutritionalAssessmentsRouter);
router.use("/patients/:id/pharmacy-entries", pharmacyEntriesRouter);
router.use("/patients/:id/transfers", transfersRouter);
router.use("/patients/:id/devices", devicesRouter);
router.use("/patients/:id/alerts", patientAlertsRouter);
router.use("/patients/:id/allergies", allergiesRouter);
router.use("/patients/:id/consents", consentsRouter);
router.use("/patients/:id/deaths", deathsRouter);
router.use("/patients/:id/procedures", proceduresRouter);
router.use("/patients/:id/interconsults", interconsultsRouter);
router.use("/patients/:id/care-plans", carePlansRouter);
router.use("/patients/:id/controlled-substances", controlledSubstancesRouter);
router.use("/patients/:id/dispensations", dispensationsRouter);
router.use("/backup", backupRouter);
router.use("/staff", staffRouter);
router.use("/audit", auditRouter);
router.use("/alerts", alertsRouter);
router.use("/beds", bedsRouter);
router.use("/notifications", sinanNotificationsRouter);
router.use("/internal-notifications", internalNotificationsRouter);
router.use("/reports", reportsRouter);
router.use("/tempos-metas", temposMetas);
router.use("/inventory", inventoryRouter);

export default router;
