// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prontuario-tabs/GroupedTabs.tsx": () => import("../components/mockups/prontuario-tabs/GroupedTabs.tsx"),
  "./components/mockups/upa-dashboard/LightMode.tsx": () => import("../components/mockups/upa-dashboard/LightMode.tsx")
};
